# Generated by Django 5.0.6 on 2024-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(max_length=50)),
                ('tyre_condition', models.CharField(max_length=50)),
                ('make_year', models.IntegerField()),
                ('owner_type', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50)),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transmission_type', models.CharField(max_length=50)),
                ('body_color', models.CharField(max_length=50)),
                ('service_record', models.TextField()),
                ('insurance', models.CharField(max_length=100)),
                ('registration_certificate', models.CharField(max_length=50)),
                ('accessories', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
